### PR TITLE
[debian_buster] Update to 80.0.3987.122

### PR DESCRIPTION
**Pull request by ghost**
This still needs some test builds to verify the rest but the patch validator should be happy.

### CODE REVIEW

**Comment by ghost** [comment]
Still no successful build but I am getting closer with each fix.

**Comment by ghost** [comment]
Ugh. I give up. I can't resolve a problem with the re2 library. The one shipped with Debian Buster is too old due to changes in the API that Chromium now relies on and I cannot get it to build if I try to use the included re2 library. I will leave this open for someone else to try to resolve the problem.

**Comment by ghost** [comment]
@tangalbert919 Any ideas if you could take a look at upgrading to 80? I'm unable to make further progress.

**Comment by tangalbert919** [comment]
I'll take a look, and send a PR to your fork when I finish.

**Comment by ghost** [comment]
Sure. I'll also bump the version since there's now an update available.

**Comment by ghost** [comment]
Done.

**Comment by ghost** [comment]
I forgot to include a simple patch for a compile error I found earlier that results from a new upstream patch from Debian. It is now.

**Comment by ghost** [comment]
I had the idea of doing a hack to fix the GetRE2 visibility though I'm not happy with this method it does seem to work. Essentially it would hack the private API into the public space for that file so it can see it and use it. But I don't know what other problems that could create. This is the patch I came up with:

http://dpaste.com/0YK72WZ

**Comment by ghost** [comment]
Ok so my hack allowed it to compile but I still need a final solution to the RE2 problem. Hm.

**Comment by Eloston** [comment]
@braewoods I haven't looked into the details yet, but why can't we just use the bundled version of `re2` for now? See https://github.com/ungoogled-software/ungoogled-chromium-debian#notes-on-updating-older-branches

**Comment by ghost** [comment]
@Eloston it now builds against debian 10. All that's left is to test the resulting build. It should be ready for merging but let me know if there's anything else blocking the merge.

**Comment by ghost** [comment]
Please wait a bit longer to merge. I'm testing an addition to the exclusions list that will hopefully fix the check for prebuilt binary files.

**Comment by ghost** [comment]
Done. I'm ready to be merged unless there's something I missed.

**Pull request closed without merging**
