### PR TITLE
Update to Ungoogled Chromium 114.0.5735.198-1

### PR DESCRIPTION
**Pull request by SugaryHull**
I still haven't received a response on whether y'all want the SQL and pdfium patches fixed for this pull request. Regardless, I've confirmed that my changes build in a fresh chroot of Debian 12 and that the package list for Ubuntu Jammy seems to directly track with the packages needed for Debian 12. It's just a matter of making the CI happy now along with possibly fixing the SQL and pdfium patches. I also haven't had time to test the binaries, so some help with that would be appreciated. Constructive criticism and other contributions are also greatly appreciated.

### CODE REVIEW

**Comment by PF4Public** [comment]
> haven't received a response on whether y'all want the SQL and pdfium patches fixed for this pull request

hmm, really?

I think we should wait for @braewoods to review your PR.

**Comment by ghost** [comment]
I would prefer the pdfium system patch being fixed. As for SQL, I don't even know why we even have it. It's a hold over from an old patch.

**Comment by ghost** [comment]
Seems both patches are still needed. See here for why the SQL patch exists: https://github.com/yuzibo/riscv-chromium-patch/blob/main/0005-sql-make-VirtualCursor-standard-layout-type.patch

**Comment by SugaryHull** [comment]
> Seems both patches are still needed. See here for why the SQL patch exists: https://github.com/yuzibo/riscv-chromium-patch/blob/main/0005-sql-make-VirtualCursor-standard-layout-type.patch

It looks like Debian has a [SQL patch](https://sources.debian.org/patches/chromium/114.0.5735.198-1~deb12u1/fixes/clang-and-gcc11.patch/) from Gentoo that wasn't labeled as such. I'll include that.

**Comment by SugaryHull** [comment]
Just updated the pdfium patch. Testing if it compiles now

**Comment by SugaryHull** [comment]
Looks like the clang version check bypass needs to be updated to make the CI happy
```
WARNING: Patch failed validation: disable-clang-version-check.patch
DEBUG: Specifically, file "tools/clang/scripts/update.py" failed validation: Line '      if force_head_revision == '':' does not match context line '      return 0' from patch
DEBUG: PATCH_BIN env variable is not set
DEBUG: Output of "patch --dry-run" for this patch on this file:
checking file tools/clang/scripts/update.py
Hunk #1 FAILED at 355.
1 out of 1 hunk FAILED

ERROR: ***FAILED VALIDATION; SEE ABOVE***
```

**Comment by SugaryHull** [comment]
One more issue and then I think it's ready. I made the same mistake as last time and updated the Ungoogled Chromium submodule to the Windows .199 revision instead of the Linux/macOS .198 revision. I'll fix that and test the build again.

**Pull request merged**
