### PR TITLE
Build 78.0.3904.97-2 for Ubuntu 19.04 (disco)

### PR DESCRIPTION
**Pull request by riyad**

### CODE REVIEW

**Comment by riyad** [comment]
The build currently fails after ~3min with the following error:
```
[...]
./out/Release/gn gen out/Release --args="host_toolchain=\"//build/toolchain/linux/unbundle:default\" custom_toolchain=\"//build/toolchain/linux/unbundle:default\" host_cpu=\"x64\" clang_use_chrome_plugins=false
closure_compile=false enable_hangout_services_extension=false enable_hevc_demuxing=true enable_mdns=false enable_mse_mpeg2ts_stream_parser=true enable_nacl=false enable_nacl_nonsfi=false enable_one_click_signin=
false enable_reading_list=false enable_remoting=false enable_reporting=false enable_service_discovery=false enable_widevine=true exclude_unwind_tables=true fieldtrial_testing_like_official_build=true google_api_
key=\"\" google_default_client_id=\"\" google_default_client_secret=\"\" optimize_webui=false safe_browsing_mode=0 treat_warnings_as_errors=false use_official_google_api_keys=false use_unofficial_version_number=
false  is_debug=false use_goma=false use_ozone=false use_sysroot=false use_openh264=false use_libjpeg_turbo=true use_custom_libcxx=false use_gnome_keyring=false use_unofficial_version_number=false enable_vr=fals
e enable_swiftshader=false optimize_webui=false linux_use_bundled_binutils=false  use_gio=true use_vaapi=true use_pulseaudio=true link_pulseaudio=true enable_widevine=true v8_enable_backtrace=true use_system_zli
b=true use_system_lcms2=true use_system_libjpeg=true use_system_freetype=true use_system_harfbuzz=true use_system_libopenjpeg2=true use_jumbo_build=true jumbo_file_merge_limit=8 proprietary_codecs=true ffmpeg_br
anding=\"ChromeOS\" fieldtrial_testing_like_official_build=true is_clang=true use_cups=true use_kerberos=false use_lld=true enable_ac3_eac3_audio_demuxing=true " --fail-on-unused-args
ERROR Unresolved dependencies.       
//third_party/perfetto/gn:zlib(//build/toolchain/linux/unbundle:default)
  needs //third_party/zlib:zlib_config(//build/toolchain/linux/unbundle:default)
```

@Eloston I'm not sure what to do. :confused: I've checked that `zlib1g-dev` is installed.

**Comment by Eloston** [comment]
If you missed it, `debian_buster` is updated and working, so you shouldn't have any problems now.

**Comment by riyad** [comment]
@Eloston, thanks! I might have been a little hasty. :sweat_smile: I updated the PR and it built with no issues this time. :+1:

**Review by Eloston — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
