### PR TITLE
Updated debian/control 'Breaks' and 'Replaces' 

### PR DESCRIPTION
**Pull request by ghost**
Changed the Breaks and Replaces section for ungoogled-chromium-sandbox

### CODE REVIEW

**Comment by ghost** [comment]
What purpose does this serve?

**Comment by Eloston** [comment]
Thanks for pointing out the problematic package relationships. I understand the change from `chromium` to `ungoogled-chromium` (which fixes our package relationships to be more like that of the original packages), but I think we need to more carefully consider the semantics here. There are two loopholes that come to mind:

1. `ungoogled-chromium-sandbox` is probably not compatible with `chromium`, so we need to add `chromium` to `Breaks`. This can arise if the user is switching between `chromium` and `ungoogled-chromium`.
2. Users may still want to switch from `ungoogled-chromium` to `chromium`, but you have a `Replaces` for `chromium-sandbox` that would make the dependency resolver fail because of the behavior in [section 7.6.2 of the Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-relationships.html#replacing-whole-packages-forcing-their-removal). Simply removing the entry in `Replaces` is not quite correct because of the behavior documented in [section 7.6.1 of the Policy Manual](https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting-files-in-other-packages). Instead, I think we should remove `chromium-sandbox` from `Replaces` AND add it to `Conflicts` (Conflicts is documented in [section 7.4](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-conflicts))

I am by no means a packaging expert, so please let us know if there are any holes in my logic.

**Comment by ghost** [comment]
@braewoods, if the relationships section for the packages is incorrect, this can cause a problem for the users.

Take this example: An older version of ungoogled-chromium is used while a newer version of ungoogled-chromium-sandbox is also installed. This would not be supported but due to the relationship specification of the package, this problem would not be detected and ungoogled-chromium-sandbox would (probably) not function.

This is a rare case but something to keep in mind nonetheless. It is vital to get the relationships of packages right, as it may result in a mess.

**Comment by ghost** [comment]
@Eloston, I appreciate the thought you have put into this, however if what you’re saying is correct, should we apply this idea to the other packages as well? (e.g ungoogled-chromium-common)

**Comment by Eloston** [comment]
> should we apply this idea to the other packages as well? (e.g ungoogled-chromium-common)

Yeah, the same situation should apply to common, sandbox, and driver.

**Comment by ghost** [comment]
Okay I have updated the changes - please review this pull request. @Eloston

**Review by Eloston — APPROVED** [review]
I think this should work, thanks :+1:

**Pull request merged**
