### PR TITLE
[ubuntu_focal] Update to 81.0.4044.113-1

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Eloston — APPROVED** [review]
:+1:

**Comment by calvinbui** [comment]
Hi @braewoods, when can we expect focal on the PPA?

**Comment by Eloston** [comment]
@calvinbui Focal just released two days ago, so 81.0.4044.122 will be the first Focal version to have a tag. I think @braewoods will then add it to the PPA.

**Comment by ghost** [comment]
@calvinbui @Eloston I was planning to replace my PPA with the OBS once I was able to iron out the issues. It solves a lot of the challenges I keep running into with the PPA that seems to cause build failures at times.

**Comment by Eloston** [comment]
@braewoods I think that's perfectly reasonable, considering users can add OBS projects as an APT source.

**Pull request merged**
