### PR TITLE
ubuntu_disco: Update ungoogled-chromium version to 74.0.3729.136-1

### PR DESCRIPTION
**Pull request by riyad**

### CODE REVIEW

**Review by Eloston — APPROVED** [review]
Generally I'd like to stick strictly to tags for new releases, but this case is probably fine. Thanks

**Comment by riyad** [comment]
hmm ... I'm not sure I understand what you mean. There was a new "release" of ungoogled-chromium (although only a patch version). Should I wait for the next major release?

**Comment by Eloston** [comment]
The commit you updated to wasn't tagged. You updated to a commit after the tag.

**Comment by riyad** [comment]
Ahh ... now I understand. :slightly_smiling_face:

**Pull request merged**
