### PR TITLE
[DRAFT] Update to Ungoogled Chromium 120.0.6099.129-1

### PR DESCRIPTION
**Pull request by SugaryHull**
This is currently a draft PR. I know of at least one more patch that I need to implement involving Debian Bookworm's version of Freetype. In the meantime, I'm posting this so I can possibly get some help fixing this error in the actual packaging. It builds and links Chromium itself, but fails to run domain_substitution.py afterwards with the following errors. I didn't have this issue when packaging Chromium 114 and can't seem to find any changes made to the script itself that would cause this. I've confirmed this issue on my personal Debian 12 system and on a different system in a fresh Debian 12 chroot.

```
Traceback (most recent call last):
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 370, in <module>
    main()
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 366, in main
    args.callback(args)
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 319, in _callback
    revert_substitution(args.cache, args.directory)
  File "/home/alex/src/ungoogled-chromium-debian_SugaryHull/debian/submodules/ungoogled-chromium/utils/domain_substitution.py", line 288, in revert_substitution
    extract_tar_file(domainsub_cache, extract_path, None)
TypeError: extract_tar_file() missing 1 required positional argument: 'skip_unused'
make[1]: *** [debian/rules:149: override_dh_prep] Error 1

### CODE REVIEW

**Comment by iskunk** [comment]
Hello @SugaryHull,

Note that the `extract_tar_file()` function in `ungoogled-chromium/utils/_extraction.py` was updated to take a new `skip_unused` argument, but the call to this function in ` domain_substitution.py` was not updated accordingly.

(I also noticed this with the call to `downloads.unpack_downloads()` in `ungoogled-chromium-windows/build.py`)

**Comment by SugaryHull** [comment]
> Hello @SugaryHull,
> 
> Note that the `extract_tar_file()` function in `ungoogled-chromium/utils/_extraction.py` was updated to take a new `skip_unused` argument, but the call to this function in ` domain_substitution.py` was not updated accordingly.
> 
> (I also noticed this with the call to `downloads.unpack_downloads()` in `ungoogled-chromium-windows/build.py`)

I see. Forgive me for asking if this turns out to be a silly question. Would this be an issue with ungoogled-chromium or the way `domain_substitution.py` is executed in `debian/rules`?

**Comment by iskunk** [comment]
> I see. Forgive me for asking if this turns out to be a silly question. Would this be an issue with ungoogled-chromium or the way `domain_substitution.py` is executed in `debian/rules`?

The issue is in ungoogled-chromium's Python code, but I believe only the `debian/rules` file is doing the `domain_substitution.py revert` operation that leads to the error. (That is to say, the error is occurring only in less-common codepaths, or else it would have been fixed already)

**Comment by SugaryHull** [comment]
> The issue is in ungoogled-chromium's Python code, but I believe only the `debian/rules` file is doing the `domain_substitution.py revert` operation that leads to the error. (That is to say, the error is occurring only in less-common codepaths, or else it would have been fixed already)

Should I open an issue or just comment out the revert call in `debian/rules` for the time being? There doesn't seem to be any open issues related to this issue.

**Comment by iskunk** [comment]
> Should I open an issue or just comment out the revert call in `debian/rules` for the time being? There doesn't seem to be any open issues related to this issue.

I would say, go ahead and open an issue/PR. It's a bug, and it directly affects your work... may as well get it fixed.

**Comment by SugaryHull** [comment]
Closing this PR to work on 120.0.6099.199-1, as that has been released for Debian 12

**Pull request closed without merging**
