### PR TITLE
[ubuntu_bionic] Update to 81.0.4044.92-2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeds but fails during linking. Somehow it pulled in system icu references. Hm.

**Comment by Eloston** [comment]
> Build succeeds but fails during linking. Somehow it pulled in system icu references. Hm.

Is it because of adding `debian/patches/system/convertutf.patch`?

**Comment by ghost** [comment]
More than likely. I thought I could get it to work with the embedded ICU.

**Comment by ghost** [comment]
It's fixed.

**Review by Eloston — APPROVED** [review]
Nice, thanks :+1:

**Pull request merged**
