### PR TITLE
README Rework

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `bullseye`

  - `sid`

  - `focal`

  - `impish`

  <br>

- **Update Description**

  `Ungoogled Chromium packaging for Debian & Ubuntu`

  <br>

- **Choose A License**

  **⤷** *https://choosealicense.com/licenses/*

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`
  
  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Uncompressed documentation into dedicated files

- Moved README into standard location to allow for relative links

- Added quicklinks

- Added supported release badges

- Added version number to supported releases

- Linked release histories for debian / ubuntu

- Streamlined installation instructions

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/ungoogled-chromium-debian

### CODE REVIEW

**Comment by PF4Public** [comment]
What value does it bring for a barely maintained repository?

**Comment by ElectronicsArchiver** [comment]
To be more maintained.

No but what kind of question is that, changes don't 
change in meaning depending on how maintained the 
repository is.

I have used this repo many times and have been mislead
by the documentation quite a bit so I thought I might
as well improve it.

**Comment by PF4Public** [comment]
Sorry, if my question sounded offending, I didn't mean anything like that.

**Comment by ElectronicsArchiver** [comment]
> Sorry, if my question sounded offending, I didn't mean anything like that.

I'm sorry as well~

Small writeup for design reasons:

- README only contains general points of interests such as:
  - Supported version a user could have
  - Different actions they might take ( install the package , find out more about what exactly is supported , build the packages themselves )
  - A small description of what the repository's file content entails
- The documentation is split up into bite-sized pieces that only show what is relevant to the file topic
- The installation is streamlined to have the user redirect / choose the prepeartion steps for their discribution and then continue with the non-unique updating / install-the-package part

**Comment by ghost** [comment]
Do not merge. I will review this later. I am currently trying to get this building.

**Comment by ElectronicsArchiver** [comment]
@braewoods So when is this `later` you were talking about?

**Comment by ghost** [comment]
I don't particularly like the approach taken here. The git root is used also for building packages directly so that was part of why I used a single file for all the documentation. In the event of a conflict between chromium and our own additions there would be problems.

Can you restructure your work under debian directory somewhere? Or even move them to a hidden folder? I also plan to remove Impish since it is EOL or close to it so I would prefer the references to it also be removed.

**Comment by ElectronicsArchiver** [comment]
> I also plan to remove Impish since it is EOL or close to it so I would prefer the references to it also be removed.

Sure~

> The git root is used also for building packages directly so that was part of why I used a single file for all the documentation. In the event of a conflict between chromium and our own additions there would be problems.

Well, **are there any conflict even**?

Also why are you building in the root anyways?
Why not just have a `Build` folder like 99% of
other projects?

> Can you restructure your work under debian directory somewhere?

You want the `Documentation` folder in there, but the README as well?

> Or even move them to a hidden folder?

`.Documentation` ?

**Comment by ghost** [comment]
Because this is how all Debian or Ubuntu packages are ultimately built. The debian folder is placed in the root of the upstream source code.

**Comment by ElectronicsArchiver** [comment]
How does that prevent a `Build` folder exactly?

The upstream would simply have to be cloned 
in said folder, same for the debian folder..

**Comment by ElectronicsArchiver** [comment]
*Also what about the other `2` questions?*

**Comment by ghost** [comment]
We used to expect people to copy the debian folder to somewhere else before attempting anything but I found it made it more difficult for me to experiment with changes and fixes.

**Comment by ghost** [comment]
Merged as a consolidated commit in another PR. For some reason a direct merge was modifying existing patches which was probably not intended.

**Comment by ElectronicsArchiver** [comment]
> Merged as a consolidated commit in another PR.

So you are saying instead of telling me to reduce this commit to the documentation changes only or having me make a cherry picked branch you choose to copy paste my changes in #305?

While you `@ElectronicsArchiver` in the title that still robs me from the contributors history.

As you don't have an `AUTHORS` file I don't consider that a valid way of accepting my changes.

Please revert your pull request and let me adjust this one.

**Comment by ghost** [comment]
Reverted.

**Comment by ElectronicsArchiver** [comment]
@braewoods Thank you, I adjusted my PR branch to have the docs in `.github` you can open the PR again if you want.

**Comment by PF4Public** [comment]
> While you `@ElectronicsArchiver` in the title that still robs me from the contributors history.

Is it so important to you? Are you after "contributors history" instead of "improving the documentation" after all? Why does "improving documentation" have to consist of 15 commits then?

**Comment by ElectronicsArchiver** [comment]
> Why does "improving documentation" have to consist of 15 commits then?

It doesn't? I can squash them down if you want.

> Is it so important to you? Are you after "contributors history" instead of "improving the documentation" after all?

Sorry I like being credited for the work I do.
Or do you not like abiding by copyright law?

**Comment by PF4Public** [comment]
> It doesn't? I can squash them down if you want.

Please be so kind. Also a commit message fully describing your efforts (not in 2 words) would be great. Thanks!

**Pull request closed without merging**
