### PR TITLE
[debian_sid] Update to 80.0.3987.149-2

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Doing a test build first. Failed to install dependencies so going to try updating to Clang 10.

**Comment by ghost** [comment]
@Eloston I'm getting a fair number of new warnings from Clang 10, all from a single warning type. Should we try to patch them at all? They look like this:
../../third_party/pdfium/core/fpdfapi/page/cpdf_contentmarks.cpp:112:19: warning: loop variable 'pMark' of type 'const fxcrt::RetainPtr<CPDF_ContentMarkItem>' creates a copy from type 'cons
t fxcrt::RetainPtr<CPDF_ContentMarkItem>' [-Wrange-loop-construct]
../../third_party/pdfium/core/fpdfapi/page/cpdf_contentmarks.cpp:112:8: note: use reference type 'const fxcrt::RetainPtr<CPDF_ContentMarkItem> &' to prevent copying

**Comment by ghost** [comment]
I'm thinking of attempting to create a patch for this. I don't think Debian upstream will patch this for awhile since Clang 10 is so new.

**Comment by ghost** [comment]
Wow. A lot of warnings spam. I am going to need to disable a few and try a rebuild out.

**Comment by ghost** [comment]
I think I found a patch that can be removed. It sets a flag for Clang that is no longer available or was only available for GCC. I'll retest with a new build.

**Comment by ghost** [comment]
@Eloston I think it's ready for merging. I decided to just disable the new warnings for now as I think Debian or Chromium will eventually patch them properly.

**Review by Eloston — APPROVED** [review]
Awesome, thanks for upgrading to LLVM 10 and handling Python 2 gracefully!

It's a little strange that there are warnings popping up with LLVM 10 considering Google usually builds Chromium with unreleased versions of LLVM. Maybe it's because we told GN to use the unbundled toolchain which has more conservative flags; I'm not sure. Regardless, you're right that Debian or Chromium will catch up and fix those warnings.

**Pull request merged**
