### PR TITLE
Update to Ungoogled Chromium 120.0.6099.199-1

### PR DESCRIPTION
**Pull request by SugaryHull**
No significant changes in patches from my draft PR for 120.0.6099.129-1 besides removing the now unnecessary _extraction.py patch for Ungoogled Chromium itself. Builds, installs, and runs on my Debian 12 system with no issues and reports resonable benchmark results for my configuration.

### CODE REVIEW

**Comment by PF4Public** [comment]
What was the reason for re-enabling tflite? AFAIK it was intentionally disabled: https://github.com/ungoogled-software/ungoogled-chromium/blob/fe594685bf3983ea9cf698e347c62e33d0665622/flags.gn#L1

**Comment by SugaryHull** [comment]
> What was the reason for re-enabling tflite? AFAIK it was intentionally disabled: https://github.com/ungoogled-software/ungoogled-chromium/blob/fe594685bf3983ea9cf698e347c62e33d0665622/flags.gn#L1

That was a remnant of my attempts at troubleshooting Tensorflow failing to build. It turned out to be an issue with the Debian version of libre2-9 and was fixed by switching to the bundled version. The commit name is misleading. I actually just removed the flag disabling tflite in the Debian packaging and titled the commit under the assumption that that flag was enabled by default, but I didn't actually enable tflite anywhere. Apologies for the confusion.

**Comment by PF4Public** [comment]
@SugaryHull I assume the issue you were facing with previous PR was fixed, right?

I think we're good to merge. @braewoods @networkException

**Comment by SugaryHull** [comment]
> @SugaryHull I assume the issue you were facing with previous PR was fixed, right?

Yep

**Pull request merged**
